### ISSUE TITLE
Possibility to move tor outside 127.0.0.1:9081

### ISSUE THREAD

**Issue by KrzysztofHajdamowicz** [deeponion/deeponion#20]
# Issue Description
When machine is running multiple backed-by-tor-cryptocurrencies, they race for port 127.0.0.1:9081/tcp

# Expected behavior
Ability to move this tor instance to another TCP port so currencies will not collide

# Example log message
```
May 27 12:48:51.144 [warn] Could not bind to 127.0.0.1:9081: Address already in use. Is Tor already running?
```

# How to reproduce
Start, for example, PRiVCY daemon, then DeepOnion Daemon. DeepOnion will complain about TCP port being used

**Comment by aitorp6** [comment]
PRiVCY copied the 99.99% of the code of DeepOnion, also the port. So maybe they should change it, not us.

**Comment by KrzysztofHajdamowicz** [comment]
IMO, it's not the cause, is it wheter deeponion or PRiVCY's fault. That's not the case.
Case is to make this configurable, so user can configure this layer of app and adjust it to his/her needs.

**Comment by nezero** [comment]
I think you are missing @aitorp6's point.

The default configuration of DeepOnion is to run Tor and configure it to use port 9081 for the TorSocks proxy service. This is non standard so it should not conflict with any other implementation of Tor. As some projects have forked our project without understanding how the privacy of DeepOnion works, they have created a problem that did not exist before.

This is configurable and is considered and an advanced use case, outside the scope of normal usage, hence there is no user guide on how to do it.

If you read all the documentation you will find all the info you need to configure it.

**Comment by nezero** [comment]
Our DeepSend release will include a change to allow your tor SocksPort `-torport` to be configurable as well as the port of the hidden service.

E.G.

`./DeepOniond  -port=17571 -torport=9082 -rpcport=18581 -daemon`
