### ISSUE TITLE
Testnet

### ISSUE THREAD

**Issue by thohemp** [deeponion/deeponion#23]
Is a testnet with nodes available?

BTW: issue pre-text is configurated for litecoin:

```
<!-- This issue tracker is only for technical issues related to Litecoin Core.

General litecoin questions and/or support requests and are best directed to the [litecointalk.io forums](https://litecointalk.io/).

...
```

**Comment by nezero** [comment]
Testnet is not running at the moment, we will reset testnet soon as we have started DeepSend development and will need it for testing.

Thanks for notifying us about the pretext i'll leave the ticket open until @deeponion changes it.

**Comment by thohemp** [comment]
Referening the referenced commit above, this can get closed.
