### ISSUE TITLE
Unable to run Wallet on Mac OSX 10.12.6  Sierra

### ISSUE THREAD

**Issue by lukzluthor** [deeponion/deeponion#37]
<!-- This issue tracker is only for technical issues related to DeepOnion.

General DeepOnion questions and/or support requests and are best directed to the [DeepOnion forums](https://deeponion.org/community).

For reporting security issues, please contact the DeepOnion developers in the DeepOnion forums or alternatively you can email us at info@deeponion.org.
 The pre-compiled binaries do not run on Max OSX 10.12.6 Sierra.

I was able to download the source and compile it to run the QT wallet but not the DV. I am not sure where the code for that is. Anyway,

I started with a fresh install of brew. Then I followed the instructions to compile the current bitcoin core client.

I made sure that it compile and deployed before proceeding.
I found out that I could not use the current version of boost. But I found an article that outlined installing with boost 1.55

so I reinstalled boost.

brew install boost@1.55
./configure --with-boost-libdir=/usr/local/Cellar/boost/1.55.0/lib

export BDB_PREFIX='/db4'
  ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" 

brew install librsvg
brew install zeromq
 
git clone --recursive https://github.com/deeponion/deeponion.git
 cd deeponion

Install Berkeley DB
./contrib/install_db4.sh 

./autogen.sh
./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" 
make

It is recommended to build and run the unit tests:

make check

You can also create a .dmg that contains the .app bundle (optional):

make deploy

Installation into user directories (optional):

make install

I do have a .dmg file with a working wallet.

let me know...

LukzLuthor

**Comment by nezero** [comment]
Please use the forum for support tickets.

https://deeponion.org/community/support-tickets/open
