### ISSUE TITLE
Error: Cannot resolve -external onion address: 'rzwgjwnox3hqzlctrsspqf4vzzi5a4ywibmboj354molyket4yutqaqd.onion'

### ISSUE THREAD

**Issue by leshacat** [deeponion/deeponion#38]
Error: Cannot resolve -external onion address: 'rzwgjwnox3hqzlctrsspqf4vzzi5a4ywibmboj354molyket4yutqaqd.onion'

**Comment by nezero** [comment]
Please provide some more info or I will close the issue.
