### ISSUE TITLE
Compile / Build problem

### ISSUE THREAD

**Issue by goodthebest** [deeponion/deeponion#51]
I'm having issues while compiling from the source here is the error screen shot when I MAKE

OS: Ubuntu 18.04

![image](https://user-images.githubusercontent.com/1715740/82643665-5f055a80-9c29-11ea-9821-03d11970a648.png)

**Comment by nezero** [comment]
Just out of curiosity are you setting up a mining pool that includes ONION mining?

You have missed `--recursive` when checking out the code.

https://github.com/deeponion/deeponion/blob/master/doc/build-unix.md

`git clone --recursive https://github.com/deeponion/deeponion.git`

You can fix this by dropping the repo and using the the command above or by running.

`git submodule init`
`git submodule sync`
`git submodule update`

Then run your `autogen.sh` and `./configure` scripts again before `make`.

**Comment by goodthebest** [comment]
@nezero yes setting up mining pool? Is there any particular line I must take?

**Comment by nezero** [comment]
No. Though if you come to our forums (if not already), we have people experienced in setting the up and you could let community know about your pool.

**Comment by goodthebest** [comment]
Is your forum on discord?
