### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by pinpins** [deeponion/deeponion#74]
Hello,

ubuntu 16.04

`
validationinterface.cpp:100:152: error: ‘boost::placeholders’ has not been declared
     g_signals.m_internals->NewPoWValidBlock.disconnect(boost::bind(&CValidationInterface::NewPoWValidBlock, pwalletIn, boost::placeholders::_1, boost::placeholders::_2));`

**Comment by nezero** [comment]
What version of boost is on your system?

The Travis CI [build](https://travis-ci.com/github/deeponion/deeponion/jobs/423729018) is passing on Ubuntu 18.04 with Boost 1.65.1.

If you're unable to upgrade your version of boost I would suggest using the [prebuilt](https://github.com/deeponion/deeponion/releases/download/v2.2.0/DeepOnion-2.2.0-x86_64-linux-gnu.tar.gz) version or building dependencies yourself and building the statically linked binary.

https://github.com/deeponion/deeponion/tree/master/depends

E.G. (Note: may not be exact.)
cd depends
make
..
./configure --prefix=`pwd`/depends/x86_64-linux-gnu
make

**Comment by pinpins** [comment]
Thanks, those steps didn't help, so in the end just installed it on Ubuntu 18.04.
