### ISSUE TITLE
Tor 0.3.4.x is supported until June switch to Tor 0.3.5.x (long-term support until 2022)

### ISSUE THREAD

**Issue by DeepBrotherhood** [deeponion/deeponion#9]
Hi, just wanted to remember ;)

Deeponion always run Tor 0.3.4.0-alpha-dev. Current is 0.3.4.11
Depponion could just bring out Tor updates more often and not just 1 time a year.

**Comment by nezero** [comment]
This is not the place for a discussion like this. Please use the forums.
